### ISSUE TITLE
DataFrames Cheatsheet review

### ISSUE THREAD

**Issue by kescobo** [tk3369/www.ahsmart.com#2]
First off, this is awesome - I will definitely print one and put it on my wall :+1:. I just have a couple of suggestions:

- I don't know what `sibsp` is. It's probably clear in the context of the titanic dataset, but things like `sex` `class` and `fare` all seem like good options, since they can probably be intuited even if a person isn't familar with the dataset. I can understand not wanting to reuse the same ones over and over, but if there are other options, I think it would be worth using them (or just explain `sibsp` better in the help text)
- under "Select observations" section, you might want to mention that you can use `unique!` to mutate to be consistent. 
- same section - I often use `unique!(df, [cols...])` syntax, which only checks certain columns for uniqueness. Might be worth adding.
- Not totally clear what that weird "R" symbol - indexing means. Is it just row-wise? Or related to R language?
- Also, that syntax can also be used to index columns at the same time - is that worth a note? (I realize space is limited)

**Comment by tk3369** [comment]
The reason for using `sibsp` and `parch` for `stack` is that they have the same data type. I don't really care much about the context since the main purpose is to remind people about the syntax. Just curious, how much are you bothered by this? 

> under "Select observations" section, you might want to mention that you can use unique! to mutate to be consistent.

👍 

> same section - I often use unique!(df, [cols...]) syntax, which only checks certain columns for uniqueness. Might be worth adding

Interesting. I don't know about this syntax before. It seems to be a somewhat "dangerous" usage since some data get lost? Under what circumstances do you want to use this feature?

> Not totally clear what that weird "R" symbol - indexing means. Is it just row-wise? Or related to R language?

Haha... good catch. I was in a hurry to make it look nice and didn't pay attention to what it means. I think it came to my mind because in this simple syntax `df[1,2]` for which the indices are just numbers. Any suggestion?

> Also, that syntax can also be used to index columns at the same time - is that worth a note? (I realize space is limited)

Yes, I can add.

**Comment by tk3369** [comment]
See updated cheat sheet at #3

**Comment by kescobo** [comment]
> Just curious, how much are you bothered by this?

Not a lot, just a minor stumbling block. From a usability perspective, it would just be more intuitive if I didn't have to wonder about the data type.

> Interesting. I don't know about this syntax before. It seems to be a somewhat "dangerous" usage since some data get lost? Under what circumstances do you want to use this feature?

Yeah, can lose data, but sometimes I want this. For example, I have a longitudinal dataset of subjects, and I just want to use the first time-point from each subject to do some cross-sectional analysis, so I do 

```
sort!(df, :timepoint)
crosssection = unique(df, :subject)
```

> Any suggestion?

Nope, sorry :-)
